In [1]:
# 💡 NOTE: Runs this jupyter notebook from the projects root, mimicking a root run.
import os
# ⭐️ NOTE: Set num_to_move to how many directories it takes from this file to reach project root.
num_to_move = 1
os.chdir(os.getcwd().rsplit("/", num_to_move)[0])
print("RUNNING FROM: ->>",os.getcwd())

import torch
# # Show all values when printing torch tensors.
torch.set_printoptions(threshold=torch.inf) # shows all the values when printing tensors


# Reloads external functions when its code changes into this notebook.
%load_ext autoreload
%autoreload 1
# %aimport will only reload those files
# %aimport utils.bboxes

RUNNING FROM: ->> /Users/tonyavis/Main/AI_public_projects/object_detection/yolo_v1_orig


In [2]:
import torch

In [32]:
torch.vstack((i, j))

tensor([[0.7249, 0.9565, 0.6310, 0.9056, 0.7675, 0.4716, 0.1288],
        [0.0889, 0.9546, 0.8911, 0.6110, 0.3677, 0.1560, 0.5228],
        [0.4769, 0.8832, 0.8636, 0.1984, 0.8500, 0.9339, 0.2993]])

In [35]:
base_tensor = torch.tensor([]).reshape(0, 7) # Reshape to the correct dimensions
base_tensor

tensor([], size=(0, 7))

In [36]:
i = torch.rand(2, 7)
j = torch.rand(1, 7)
print(i, "\n\n", j)

tensor([[0.2809, 0.4939, 0.6416, 0.7177, 0.3983, 0.8586, 0.9110],
        [0.3813, 0.8276, 0.4029, 0.6661, 0.3103, 0.3476, 0.9494]]) 

 tensor([[0.7223, 0.2987, 0.3857, 0.0889, 0.9291, 0.6365, 0.7771]])


In [39]:
torch.vstack((base_tensor, j, i, torch.rand(2, 7) ))

tensor([[0.7223, 0.2987, 0.3857, 0.0889, 0.9291, 0.6365, 0.7771],
        [0.2809, 0.4939, 0.6416, 0.7177, 0.3983, 0.8586, 0.9110],
        [0.3813, 0.8276, 0.4029, 0.6661, 0.3103, 0.3476, 0.9494],
        [0.7347, 0.0125, 0.1881, 0.3290, 0.5546, 0.2723, 0.8903],
        [0.9695, 0.1584, 0.8985, 0.7114, 0.9129, 0.8756, 0.2593]])

In [40]:
torch.tensor([1, 3, 4]).shape

torch.Size([3])